spring:
  profiles:
    active: local

---
server:
  host:
    front: localhost:8080
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/ticket_auction
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 10
      max-lifetime: 240000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: never

jwt:
  secret:
    key: ${jwt_secret_key}

cloud: # S3
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3_bucket_name}
    region:
      static: ap-northeast-2
    stack:
      auto: false


naver-cloud:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  service-id: ${SERVICE_ID}
  sender-phone: ${SENDER_PHONE}

payment:
  toss:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${SUCCESS_URL}
    fail-url: ${FAIL_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - "bean"
          - "dev"
      base-path: "/secure/actuator"



log:
  config:
    path: ./logs
    filename: ticket-auction-local
    maxHistory: 7 # 7일
    maxFileSize: 100MB
    totalSizeCap: 1GB # 로그 파일 사이즈